// Code generated by mockery v1.0.0
package ioifacemocks

import mock "github.com/stretchr/testify/mock"

// ReadAt is an autogenerated mock type for the ReadAt type
type ReadAt struct {
	mock.Mock
}

// ReadAt provides a mock function with given fields: _a0, _a1
func (_m *ReadAt) ReadAt(_a0 []byte, _a1 int64) (int, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int
	if rf, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
