// Code generated by mockery v1.0.0
package fsmocks

import jobqueue "github.com/cameronwp/glacier/jobqueue"
import mock "github.com/stretchr/testify/mock"

// Chunker is an autogenerated mock type for the Chunker type
type Chunker struct {
	mock.Mock
}

// CreateChunks provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Chunker) CreateChunks(_a0 string, _a1 string, _a2 int64, _a3 int64) ([]jobqueue.Chunk, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 []jobqueue.Chunk
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) []jobqueue.Chunk); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jobqueue.Chunk)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFilesize provides a mock function with given fields: _a0
func (_m *Chunker) GetFilesize(_a0 string) (int64, error) {
	ret := _m.Called(_a0)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
