// Code generated by mockery v1.0.0
package drainmocks

import jobqueue "github.com/cameronwp/glacier/jobqueue"
import mock "github.com/stretchr/testify/mock"

// Drainer is an autogenerated mock type for the Drainer type
type Drainer struct {
	mock.Mock
}

// Drain provides a mock function with given fields: _a0
func (_m *Drainer) Drain(_a0 jobqueue.FIFOQueuer) {
	_m.Called(_a0)
}
